### ISSUE TITLE
/* ... */ header in .sh files

### ISSUE THREAD

**Issue by zurbo** [Kerosene2000/atom-header-42#3]
Hi,
the package tries to create a header with C comments on .sh files

**Comment by TBouder** [comment]
Hi, 
I just ask for a revision with a little edit to add sh files. You can clone from here as long as it's not merge
https://github.com/TBouder/atom-header-42

**Comment by Kerosene2000** [comment]
Fixed by https://github.com/Kerosene2000/atom-header-42/pull/5, thanks to @TBouder !
