### ISSUE TITLE
ajoute espace après le login

### ISSUE THREAD

**Issue by malikoum94** [Kerosene2000/atom-header-42#6]
Bonjour,

Le header est bien généré mais au moment de la sauvegarde, il rajoute un espace entre le login et le mail.

bon courage

**Comment by Kerosene2000** [comment]
Si tu pouvais vérifier si ton login ne contient pas d'espace à la fin, va dans les settings du header pour cela.

**Comment by malikoum94** [comment]
Non que je laisse le défaut (whoami) ou que je tape mon login (sans espace), le header ce génère bien mais au moment de save il ajoute un espace... Mon login est mmazouz, peut être un problème de len

**Comment by Kerosene2000** [comment]
Tu peux me donner les plugins que tu as installés ?

**Comment by malikoum94** [comment]
liste des plugins:
-build-tools
-build-tools-make
-header-42
-linter
-linter-clang
-minimap
-norminette-linter
-save-notification

**Comment by Kerosene2000** [comment]
can you send me the output of this command please:
```
$> echo $USER | cat -e
```

**Comment by malikoum94** [comment]
echo $USER | cat -e
mmazouz$

**Comment by Kerosene2000** [comment]
fixed d299a64cbf32d2047a2680d24d9d5bc2655b2bd9
